Day19_ASP.NET_Core/MovieShop/MovieShop.MVC/Controllers/AdminController.cs
using ApplicationCore.Models.Request;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShop.MVC.Controllers
{
    public class AdminController : Controller
    {
        private readonly IMovieService _movieService;

        public AdminController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        [HttpGet]
        public IActionResult CreateMovie()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMovie(MovieCreateRequestModel model)
        {
            //check for model validation on server also
            if (ModelState.IsValid)
            {
                // save to database
                var movie = await _movieService.CreateMovie(model);
                // redirect to new created movie
                return LocalRedirect(localUrl: $"~/Movies/Details/{movie.Id}");
            }
            return View();
        }

        [HttpGet]
        public IActionResult CreateCast()
        {
            return View();
        }
        

        [HttpPost]
        public IActionResult Movie()
        {
            return View();
        }

        //[HttpPut]
        //public IActionResult Movie()
        //{
        //    return View();
        //}

        [HttpGet]
        public IActionResult Purchases()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Day19_ASP.NET_Core/MovieShop/MovieShop.MVC/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Models.Response;
using ApplicationCore.ServiceInterfaces;
using System.Threading.Tasks;

namespace MovieShop.MVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        public MoviesController(IMovieService service)
        {
            _movieService = service;
        }

        [HttpGet]
        public IActionResult Index(int id = 0)
        {
            return View();
        }

        //[HttpGet]
        //public IActionResult Index(int id)
        //{
        //    return View();
        //}

        [HttpGet]
        public IActionResult TopRated()
        {
            return View();
        }

        [HttpGet]
        public IActionResult TopRevenue()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Genre(int id)
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetailsById(id);
            return View(movie);
        }
    }
}

Day19_ASP.NET_Core/MovieShop/MovieShop.MVC/Controllers/UserController.cs
using ApplicationCore.Models.Request;
using ApplicationCore.Models.Response;
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShop.MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly ICurrentUserService _currentUserService;
        private readonly IMovieService _movieService;
        private readonly IUserService _userService;

        public UserController(ICurrentUserService currentUserService, IMovieService movieService, IUserService userService)
        {
            _currentUserService = currentUserService;
            _movieService = movieService;
            _userService = userService;
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> GetUserPurchasedMovies()
        {
            var userId = _currentUserService.UserId;
            // get the user id
            //
            // make a request to the database and get info from Purchase Table 
            // select * from Purchase where userid = @getfromcookie

            var movies = await _userService.GetAllPurchasesForUser(userId);
            return View(movies);
        }

        [HttpGet]
        public async Task<IActionResult> PurchaseMovie(int id)
        {
            var movie = await _movieService.GetMovieDetailsById(id);
            return View(movie);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PurchaseMovie(MovieDetailsResponseModel model)
        {
            
            // check if user already logged in
            if (User.Identity != null && User.Identity.IsAuthenticated)
            {
                MovieDetailsResponseModel movieInfo = await _movieService.GetMovieDetailsById(model.Id);
                PurchaseRequestModel purchaseModel = new PurchaseRequestModel
                {
                    UserId = _currentUserService.UserId,
                    MovieId = model.Id,
                    TotalPrice = movieInfo.Price,
                };

                if (ModelState.IsValid)
                {
                    await _userService.PurchaseMovie(purchaseModel);
                    return RedirectToAction("GetUserPurchasedMovies");
                }
            }
            return View();
        }

        [HttpPost]
        public IActionResult Purchase()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Favorite()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Unfavorite()
        {
            return RedirectToAction("Index");
        }

        //[HttpGet]
        //public IActionResult Favorite()
        //{
        //    return View();
        //}

        [HttpPost]
        public IActionResult Review()
        {
            return RedirectToAction("Index");
        }

        //[HttpPut]
        //public IActionResult Review()
        //{
        //    return RedirectToAction("Index");
        //}

        [HttpDelete]
        public IActionResult Delete(int userId, int movieId)
        {
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Purchase(int id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Favorite(int id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Reviews(int id)
        {
            return View();
        }
    }
}

Day19_ASP.NET_Core/MovieShop/MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShop.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShop.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>

            <partial name="_LoginInfoPartial" />
        </nav>
</header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShop.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Day19_ASP.NET_Core/MovieShop/MovieShop.MVC/Views/Shared/_LoginInfoPartial.cshtml
@using ApplicationCore.ServiceInterfaces;
@inject ICurrentUserService _CurrentUserService;
@inject IUserService _UserService;


@if (_CurrentUserService.IsAuthenticated)
{
    // FirstName LastName and Email
    <div class="navbar-collapse collapse w-100 order-3">
        <ul class="navbar-nav ml-auto">
            @if (_CurrentUserService.IsAdmin || _CurrentUserService.IsSuperAdmin)
            {
                <li class="nav-item dropdown text-capitalize">
                    <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
                       style="cursor: pointer;" aria-haspopup="true"
                       aria-expanded="false">
                        @_CurrentUserService.FullName (Admin)
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateMovie">Create Movie</a>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="CreateCast">Create Cast</a>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="Index">Home</a>
                        <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out (Admin)</a>
                    </div>
                </li>
            }
            else
            {
                <li class="nav-item dropdown text-capitalize">
                    <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
                       style="cursor: pointer;" aria-haspopup="true"
                       aria-expanded="false">
                        @_CurrentUserService.FullName
                    </a>

                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
                        <a class="dropdown-item" asp-controller="User" asp-action="GetUserPurchasedMovies">Library (@_CurrentUserService.TotalMovies)</a>
                        <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out (@_CurrentUserService.FullName)</a>
                        <a class="dropdown-item" asp-controller="Account" asp-action="Profile">View Profile (@_CurrentUserService.FullName)</a>
                        <a class="dropdown-item" asp-controller="Account" asp-action="EditProfile">Edit Profile (@_CurrentUserService.FullName)</a>
                    </div>
                </li>
            }
        </ul>
    </div>
}
else
{
    <div class="navbar-collapse collapse w-100 order-3">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item pr-4">
                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Login">Login</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-outline-primary" asp-controller="Account" asp-action="Register">Register</a>
            </li>
        </ul>
    </div>
}

Day19_ASP.NET_Core/MovieShop/MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.Response.MovieCardResponseModel

<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>